name: Sphinx

on:
  push:
    tags:
      - "**"
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Setup Environment
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        ${XDG_DATA_HOME:-~/.local/share}/pypoetry/venv/bin/pip install poetry-dynamic-versioning
        poetry install
    - name: Build Documentation
      run: |
        ./doc/build.sh
    - name: Deploy Documentation
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/master' }} || startsWith(github.ref, 'refs/tags/v')
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc/build/html
